<?php
/**
 * Danh mục nghề nghiệp — nguồn duy nhất cho bảng `jobs`.
 *
 * Dùng bởi database/update.php (máy chủ đã cài sẵn) và khớp với phần INSERT
 * trong database/schema.sql (cài mới). Thêm nghề mới thì sửa ở cả hai nơi.
 */

return array(
    'Bác sĩ',
    'Bác sĩ chuyên khoa',
    'Bảo mẫu',
    'Bảo vệ',
    'Biên đạo múa',
    'Biên dịch viên',
    'Biên kịch',
    'Biên tập viên',
    'Bồi bàn',
    'Ca sĩ',
    'Cảnh sát',
    'Cán bộ nhà nước',
    'Cán bộ văn hóa',
    'Chủ doanh nghiệp',
    'Chuyên gia môi trường',
    'Chuyên viên DevOps',
    'Chuyên viên an ninh mạng',
    'Chuyên viên bảo hiểm',
    'Chuyên viên bán hàng',
    'Chuyên viên chăm sóc khách hàng',
    'Chuyên viên du lịch',
    'Chuyên viên giáo dục',
    'Chuyên viên hành chính',
    'Chuyên viên kinh doanh',
    'Chuyên viên marketing',
    'Chuyên viên ngân hàng',
    'Chuyên viên nhân sự',
    'Chuyên viên phân tích đầu tư',
    'Chuyên viên pháp lý',
    'Chuyên viên phục hồi chức năng',
    'Chuyên viên quản lý tài nguyên',
    'Chuyên viên tài chính',
    'Công chứng viên',
    'Công nhân sản xuất',
    'Diễn viên',
    'Diễn viên múa',
    'Dược sĩ',
    'Đạo diễn',
    'Đầu bếp',
    'Điều dưỡng',
    'Giám đốc điều hành (CEO)',
    'Giám đốc khối',
    'Giảng viên đại học',
    'Giáo viên',
    'Giáo viên mầm non',
    'Giáo viên tiểu học',
    'Họa sĩ',
    'Hộ sinh',
    'Hướng dẫn viên du lịch',
    'Kế toán viên',
    'Kiểm lâm',
    'Kiểm toán viên',
    'Kiến trúc sư',
    'Kỹ sư AI/ML',
    'Kỹ sư cơ khí',
    'Kỹ sư dữ liệu',
    'Kỹ sư điện - điện tử',
    'Kỹ sư hóa học',
    'Kỹ sư mạng',
    'Kỹ sư môi trường',
    'Kỹ sư nông nghiệp',
    'Kỹ sư phần mềm',
    'Kỹ sư thủy lợi',
    'Kỹ sư xây dựng',
    'Kỹ thuật viên',
    'Kỹ thuật viên y tế',
    'Lao động phổ thông',
    'Lãnh đạo cấp cao',
    'Lễ tân',
    'Lính cứu hỏa',
    'Luật sư',
    'Shipper (Giao hàng)',
    'Người làm vườn',
    'Ngư dân',
    'Nhà báo',
    'Nhà điêu khắc',
    'Nhà nghiên cứu',
    'Nhà sản xuất âm nhạc',
    'Nhà thơ',
    'Nhà văn',
    'Nhạc công',
    'Nha sĩ',
    'Nhiếp ảnh gia',
    'Nông dân',
    'Phóng viên',
    'Phụ bếp',
    'Quản lý dự án',
    'Quản lý vận hành',
    'Quay phim',
    'Sĩ quan công an',
    'Sĩ quan quân đội',
    'Tạp vụ',
    'Tài xế',
    'Thẩm phán',
    'Thông dịch viên',
    'Thuyền trưởng',
    'Thư ký',
    'Thư viện viên',
    'Tiếp tân',
    'Trợ lý hành chính',
    'Trợ giúp viên pháp lý',
    'Trưởng phòng ban',
    'Y sĩ',
    'Blogger/Content Creator',
    'Bác sĩ thú y',
    'Chuyên viên bất động sản',
    'Chuyên viên logistics',
    'Chuyên viên PR',
    'Chuyên viên SEO',
    'Chuyên viên truyền thông',
    'Chuyên viên UX/UI Design',
    'Đầu tư tài chính tự do',
    'Freelancer (Tự do)',
    'Giáo viên dạy lái xe',
    'Giáo viên yoga',
    'HLV thể hình',
    'Kỹ sư âm thanh',
    'Kỹ sư địa chất',
    'Kỹ sư năng lượng',
    'Nhân viên cảng vụ',
    'Nhân viên kiểm soát không lưu',
    'Nhân viên kho vận',
    'Nhân viên ngân hàng đầu tư',
    'Nhân viên sự kiện',
    'Nhân viên thu ngân',
    'Nhân viên văn thư',
    'Phi công',
    'Thợ cắt tóc',
    'Thợ may',
    'Thợ mộc',
    'Thợ nề',
    'Thợ sơn',
    'Thợ sửa chữa ô tô',
    'Thợ sửa ống nước',
    'Thợ điện',
    'Thợ hàn',
    'Trang điểm viên (Makeup Artist)',
    'Chuyên viên trang điểm',
    'Nhà thiết kế thời trang',
    'Nhà thiết kế đồ họa',
    'Người mẫu',
    'MC/Dẫn chương trình',
    'Nhà sản xuất phim',
    'Kỹ sư robot',
    'Kỹ sư hàng không',
);
